# Generated by Django 5.2.8 on 2025-11-23 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('original_url', models.URLField(max_length=2048)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clicks_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=1024)),
                ('referer', models.URLField(blank=True, max_length=2048, null=True)),
                ('short_url_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='shorturl.shorturls')),
            ],
        ),
    ]
