# Generated by Django 5.2.8 on 2025-11-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturls',
            name='short_code',
        ),
    ]
