# Generated by Django 5.2.8 on 2025-11-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0002_remove_shorturls_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturls',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
