# Generated by Django 5.2.8 on 2025-11-25 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0003_shorturls_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturls',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 5, 4, 5, 21, 93090, tzinfo=datetime.timezone.utc)),
        ),
    ]
