# Generated by Django 5.2.8 on 2025-11-26 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0004_shorturls_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturls',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 6, 10, 19, 18, 532465, tzinfo=datetime.timezone.utc)),
        ),
    ]
