# Generated by Django 5.2.8 on 2025-11-27 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0005_alter_shorturls_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturls',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 7, 7, 1, 20, 902375, tzinfo=datetime.timezone.utc)),
        ),
    ]
